name: Docker Build and Push

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

env:
  IMAGE_NAME: rtex

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          echo ${{ github.sha }} > git_commit
          docker build . --file Dockerfile -t $IMAGE_NAME

      - name: Log into Github Package Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image to registries
        run: |
          GITHUB_IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME

          echo GITHUB_IMAGE_ID=$GITHUB_IMAGE_ID

          # tag for Github Registry
          docker tag $IMAGE_NAME $GITHUB_IMAGE_ID:latest
          docker push $GITHUB_IMAGE_ID